apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-productos-v3-config
  namespace: practica
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_R2DBC_URL: "r2dbc:postgresql://host.docker.internal:5432/db_productos_dev"
  DB_USERNAME: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  SERVER_PORT: "8088"
  EUREKA_CLIENT_ENABLED: "false"
