apiVersion: v1
kind: Service
metadata:
  name: ms-productos-v3-nodeport
  namespace: practica
  labels:
    app: ms-productos-v3
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088
      protocol: TCP
      name: http
  selector:
    app: ms-productos-v3
