spring:
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: oauth-server
            client-id: oauth-client
            client-secret: 12345678910
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8085/authorized"
            client-name: oauth-client
            scope: openid,profile,read,write
        provider:
          oauth-server:
            authorization-uri: http://oauth-server:9000/oauth2/authorize
            token-uri: http://oauth-server:9000/oauth2/token
            jwk-set-uri: http://oauth-server:9000/oauth2/jwks
            user-info-uri: http://oauth-server:9000/userinfo